### ISSUE TITLE
Bug: Potential cache logic issue on this repo's CircleCI config?

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/release-toolkit#139]
Hi there!

I'm an external contributor just reading the code of this repo to get a sense of it (being very interested in a8c!), so not an actual user of the release-toolkit; but while I was looking at your CircleCI config I think I spotted a potential caching issue.

### Description

The issue is you are using a different key [to restore the brew+gems cache](https://github.com/wordpress-mobile/release-toolkit/blob/develop/.circleci/config.yml#L21) than the one you're using [for saving the cache](https://github.com/wordpress-mobile/release-toolkit/blob/develop/.circleci/config.yml#L33) a couple of lines below it. Which means that CircleCI will never find a matching and previously-saved cache when trying to restore it.

### Issue Example

This can be confirmed by looking for example at [this CircleCI job](https://app.circleci.com/pipelines/github/wordpress-mobile/release-toolkit/345/workflows/35ef8330-2843-4ca6-ad03-be180733850b/jobs/335/steps) on one of the PR which doesn't change either the `.brewfile` nor the `Gemfile.lock` while the step still mentions `"No cache is found for key: …"` in the CI logs

### Suggested fix

 - either copy the key on line 21 to paste it on line 33
 - or, for a more sustainable solution, use yaml anchors & references

```diff
       - restore_cache:
           name: Restore Homebrew + Ruby Dependencies
           keys:
-            - brew-dependencies-{{ checksum ".circleci/.brewfile" }}-{{ checksum "Gemfile.lock" }}
+            - &cache_key brew-dependencies-{{ checksum ".circleci/.brewfile" }}-{{ checksum "Gemfile.lock" }}
...
       - save_cache:
           name: Cache Homebrew + Ruby Dependencies
-          key: brew-dependencies-{{ checksum ".circleci/.brewfile" }}
+          key: *cache_key
```

---

That being said, I didn't want to open a PR directly because from what I saw from recent commits and repo content, I'm guessing you're in the process of migrating to GitHub workflows so not sure if you're planning on maintaining CircleCI for long anymore? So I preferred to open an issue first, but will be happy to do a PR if you want me to.

**Comment by jkmassel** [comment]
Howdy @AliSoftware!

This is a nice catch, thanks :) 

I like the anchor / reference solution – TIL that was a thing! 😅 

Happy to approve a PR if you'd like to make one!

**Comment by AliSoftware** [comment]
@jkmassel Opened a PR, but as I mentioned above, and as you'll see in the PR #143 too, I'm not sure I'll be able to fix because (1) GitHub Actions takes over CircleCI now that you started using it and (2) your Danger job doesn't work with forks (and I don't have the rights to create a branch on your repo directly) – so there's no way to validate on my end that my changes will make CircleCI pass as expected since it will always fail for a fork
