### ISSUE TITLE
Remove the need for PROJECT_ROOT_DIR env var

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/release-toolkit#205]
We should stop relying on this env var and requiring it to be set as we could instead be able to detect that project root automatically in the actions that needs it.

At first I thought we could make use of something like `git rev-parse --show-toplevel` to detect that project root path automatically. But then I realized that I think that won't even be necessary, because [as documented in the _fastlane_ docs](https://docs.fastlane.tools/advanced/fastlane/#directory-behavior), the working directory is already guaranteed to be the project root itself for code run from actions defined in plugin like the `release-toolkit`. So we can probably just replace it with `.` and use relative paths, as the `Dir.pwd` should already be the project root folder in our context!

**Comment by jkmassel** [comment]
The environment variable is `PROJECT_ROOT_FOLDER`, for any future searchers who get very confused why they can't grep for `PROJECT_ROOT_DIR` 😜
