### ISSUE TITLE
Default `skip_glotpress` to `true` in `ios_bump_version_release`

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/release-toolkit#372]
With the [new localization tooling](https://github.com/orgs/wordpress-mobile/projects/105) we no longer rely on a local `download_metadata.swift` script for metadata localization. To account for this behavior, the `ios_bump_version_release` action has a `skip_glotpress` parameter. Both [WordPress iOS](https://github.com/wordpress-mobile/WordPress-iOS/blob/1022e0c0dec6a4f1225b8b8896f5dc7a4987bc86/fastlane/lanes/release.rb#L19) and [WooCommerce iOS](https://github.com/woocommerce/woocommerce-ios/pull/7081) are now using the new tooling and setting `true` for that configuration.

Given that not using `download_medata.swift` is the desired behavior going forward, I think we should also make `skip_glotpress` default to `true`. **Alternatively, we could wholesale remove it and ship a new major version.**

**Comment by iangmaia** [comment]
Picking up this issue 🙋‍♂️
