### ISSUE TITLE
Add configuration item for `xcconfig` with version info to `ios_get_app_version`

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/release-toolkit#380]
Currently, the action relies on the value being set in an environment variable, `PUBLIC_CONFIG_FILE`. We ought to make it explicit and ditch this easy to miss configuration.

**Comment by iangmaia** [comment]
Picking up this issue 🙋‍♂️

**Comment by mokagio** [comment]
Closed via #445.
