### ISSUE TITLE
Remove hardcoded references to `RELEASE-NOTES.txt`

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/release-toolkit#395]
We discussed internally (pdnsEh-aj-p2) that it would be nice to use `CHANGELOG.md` instead of `RELEASE-NOTES.txt`, which is the de-facto standard for tracking changes in open source projects these days.

@leandroalonso recently [noticed](104-gh-Automattic/pocket-casts-ios#discussion_r932156026) that a considerable blocker to implementing this change is the fact that the toolkit has hardcoded references to `RELEASE-NOTES.txt` in it. Example:

https://github.com/wordpress-mobile/release-toolkit/blob/b2a0ecb7276c48f167a299e78027a0196597cb56/lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_update_release_notes.rb?rgh-link-date=2022-07-28T12%3A27%3A54Z#L11

Before we can begin renaming the files, we need to remove any hardcoded reference (which will be a breaking change) and replace them with configurable parameters (maybe defaulting to `CHANGELOG.md` for convenience).

**Comment by leandroalonso** [comment]
> Before we can begin renaming the files, we need to remove any hardcoded reference (which will be a breaking change) and replace them with configurable parameters (maybe defaulting to CHANGELOG.md for convenience).

I wonder if the parameter might be optional and in the case of the absence of it we can just fallback to `RELEASE-NOTES.txt`? This way we don't have to change all the projects that use it.

**Comment by mokagio** [comment]
@leandroalonso oh yeah, good point. Thank you for raising this.

 By defaulting to `RELEASE-NOTES.txt` rather than `CHANGELOG.md` as I originally envisioned, we wouldn't make the change a breaking one. This would allow us to migrate gradually and only update the code to use the recommended `CHANGELOG.md` as the default (breaking change) at our convenience, maybe if/when all the project will have migrated.
