### ISSUE TITLE
Stop accessing `GITHUB_TOKEN` under the hood in `github_helper`

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/release-toolkit#416]
I just experienced a CI failure while my automation attempted to create a GitHub release for an internal app. The reason for the failure was a 401 from the GitHub API. This happened because neither `GHHELPER_ACCESS` nor `GITHUB_TOKEN` were available in the environment at runtime.

https://github.com/wordpress-mobile/release-toolkit/blob/24d6859170948737120f6ef12662536bee27ffe4/lib/fastlane/plugin/wpmreleasetoolkit/helper/github_helper.rb#L13-L14

While I agree that it's convenient to not have to pass tokens around when calling helper methods, by accessing them under the hood we make them invisible to our consumers, which can lead to issues such as the one I just experienced. 

I think we'd be better off incurring a more verbose API in the actions by adding parameters for all the tokens they expect, rather than risking CI failures like this one. 

Case in point, I had already experience a CI failure because of a missing token and grepped the `Fastfile` of that project for any `ENV` access that would reveal the need for others. Had `create_release` required an explicit token, I would have seen it and added it to our CI environment before retrying my deployment build.

**Comment by spencertransier** [comment]
This issue was resolved by https://github.com/wordpress-mobile/release-toolkit/pull/420 last year.
