### ISSUE TITLE
Deprecate `Fastlane::Helper::Ios::GitHelper.commit_version_bump`

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/release-toolkit#525]
The [helper](https://github.com/wordpress-mobile/release-toolkit/blob/trunk/lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb) method relies on the  `PROJECT_ROOT_FOLDER` environment variable, which is no longer meant to be used and has been removed by client apps such as WordPress iOS, https://github.com/wordpress-mobile/WordPress-iOS/pull/21859. 

Looking at it today, `commit_version_bump` seems redundant. It DRYs the message and paths for the committing a version bump, but is it actually necessary to have that logic DRYed _in a library_ when it's possible to achieve the same result with a method, e.g. see https://github.com/wordpress-mobile/WordPress-iOS/commit/f886436c4fcdbaf6d4fd3a1f65e06a3fc06b0b8e, within the project's `Fastfile`?

I propose we deprecate the helper, or at and schedule it for removal on the next major version.

**Comment by AliSoftware** [comment]
This helper method has been removed [in version 12.0](https://github.com/wordpress-mobile/release-toolkit/blob/trunk/MIGRATION.md#from-11x-to-1200) via #580
