### ISSUE TITLE
Deprecate `ios_codefreeze_prechecks` and other pre-check lanes

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/release-toolkit#576]
I've started looking at the various Simplenote apps release automation with the goal to update then and eventually support releases in CI.

Internal ref p2XJRt-3Ju-p2

One thing I just noticed is the [`ios_codefreeze_prechecks`](https://github.com/wordpress-mobile/release-toolkit/blob/33bc2c60cd6b3194455e525fea719c906373d3ed/lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_codefreeze_prechecks.rb) in Simplenote iOS.

I'm not sure if we explicitly discussed this ([a search for issues with "prechecks" brought no results](https://github.com/search?q=repo%3Awordpress-mobile%2Frelease-toolkit+prechecks&type=issues)) but I think we have decided to move on from this approach in favor of a more granular and explicit approach, where each project performs the checks it requires.

For example, [WordPress iOS individually checks for the git status being clean then switches to `trunk` if necessary](https://github.com/wordpress-mobile/WordPress-iOS/blob/7b0fb0b1e2391850c1248dad4421412a888ae893/fastlane/lanes/release.rb#L16-L23).

We could add the deprecated annotation to the lanes and then remove them whenever we'll ship a new major version.

**Comment by spencertransier** [comment]
Heh, I actually just started work on deprecating those today 😄 . The discussion to deprecate those got wrapped up in the versioning changes last fall. It was decided to not update the precheck actions for the versioning changes and instead add the actions and steps that used to be performed by the precheck actions into the repos themselves, for better clarity.

**Comment by spencertransier** [comment]
@mokagio here's the PR for the deprecations: https://github.com/wordpress-mobile/release-toolkit/pull/577
