### ISSUE TITLE
Should `release-toolkit` be a repo in the Automattic org?

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/release-toolkit#581]
I just switched Simplenote Android to fetch `release-toolkit` from a branch. I typed the URL manually and used `Automattic` only to realize it was wrong and that the repo lives in the `wordpress-mobile` org.

Now, that's not a big deal, but I wonder if it would be neater to have the repo live in the `Automattic` org. After all, we use `Automattic` as the author for all the actions already.

If we made the switch, I _think_ GitHub should redirect the URL without causing users that point to `wordpress-mobile` to get a 404.

Again, this is not a big deal, but it occurred to me so I though I'd share it here. Totally cool to leave as is, or add it to the pile of small projects to use during decompression weeks between bigger ones (AKA nice to have, we'll get there _one day_™)

@wordpress-mobile/apps-infrastructure thoughts?

**Comment by AliSoftware** [comment]
This has actually been a move we've been wanting to do for a long while, so we're already in agreement that this is a thing we should do. We just never found the time to actually do it 🙃 

See https://github.com/orgs/Automattic/projects/841/views/1?filterQuery=release-toolkit&pane=issue&itemId=50028422

**Comment by mokagio** [comment]
Neat! I should have checked, thanks for the pointer.

I added a link to this issue to the card. I'll close this to keep the least neat.
